import React from 'react';
import { FileCheck, Shield, AlertTriangle, FileText, CheckCircle2, Scale, Layers } from 'lucide-react';
import { PROTOTYPE_VASP_LABELS } from '../../../server/src/data/vaspLabels';

export const EvidenceAttributionPage: React.FC = () => {
  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Page Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center space-x-2">
            <span className="text-xs font-mono bg-blue-950 text-blue-300 px-2 py-0.5 rounded border border-blue-800">
              HYDROTRACE VASP INTELLIGENCE REGISTRY
            </span>
          </div>
          <h2 className="text-xl font-semibold text-slate-100 mt-2 flex items-center">
            <FileCheck className="w-5 h-5 mr-2 text-blue-400" />
            HydroTrace — Curated VASP Registry, Conflict Detection & Stress Standards
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            HydroTrace — Evidence-Driven Blockchain Intelligence for VASP Attribution
          </p>
        </div>
      </div>

      {/* Mandatory Legal & Methodological Disclaimer */}
      <div className="bg-slate-900 border border-slate-800 rounded-lg p-5">
        <div className="flex items-start space-x-3">
          <Shield className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
          <div className="space-y-1 font-mono text-xs">
            <h3 className="text-amber-300 font-semibold uppercase">
              Legal & Methodological Attribution Principles
            </h3>
            <p className="text-slate-300 leading-relaxed font-sans text-xs">
              Attribution scorecards generated by HydroTrace identify candidate Virtual Asset Service Providers (VASPs) through exact, deterministic on-chain deposit address matching against documented datasets.
              <strong className="text-amber-300"> Under no circumstances does on-chain attribution establish the real-world identity or ownership of the wallet.</strong>
            </p>
          </div>
        </div>
      </div>

      {/* Prototype VASP Dataset Table */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-lg p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <h3 className="text-xs font-mono uppercase text-slate-300 font-semibold flex items-center">
            <FileText className="w-4 h-4 mr-2 text-blue-400" />
            HydroTrace Curated VASP Intelligence Dataset ({PROTOTYPE_VASP_LABELS.length} Verified Records)
          </h3>
          <span className="text-[11px] font-mono text-slate-400">
            TRON MAINNET SCOPE
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left font-mono text-xs text-slate-300 border-collapse">
            <thead>
              <tr className="bg-[#0B0F19] text-slate-400 border-b border-slate-800 text-[11px]">
                <th className="py-2.5 px-3">Entity Name</th>
                <th className="py-2.5 px-3">TRON Address</th>
                <th className="py-2.5 px-3">Role</th>
                <th className="py-2.5 px-3">Evidence Sources</th>
                <th className="py-2.5 px-3">Conflict Status</th>
                <th className="py-2.5 px-3">Notes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-[11px]">
              {PROTOTYPE_VASP_LABELS.map((item, idx) => {
                const sources = item.evidenceSources || [];
                const entitySet = new Set(sources.map((s) => s.associatedEntity || item.entityName));
                const hasConflict = entitySet.size > 1;

                return (
                  <tr key={idx} className={`hover:bg-slate-800/40 ${hasConflict ? 'bg-amber-950/20' : ''}`}>
                    <td className="py-3 px-3 font-semibold text-slate-100">{item.entityName}</td>
                    <td className="py-3 px-3 text-blue-300 font-mono break-all">{item.address}</td>
                    <td className="py-3 px-3">
                      <span className="bg-blue-950 text-blue-300 px-1.5 py-0.5 rounded border border-blue-800 text-[10px]">
                        {item.walletRole}
                      </span>
                    </td>
                    <td className="py-3 px-3 space-y-1">
                      {sources.map((s, sIdx) => (
                        <div key={sIdx} className="text-[10px] text-slate-300 flex items-center space-x-1">
                          <span className="bg-slate-800 text-slate-400 px-1 rounded">{s.sourceType}</span>
                          <span className="text-slate-200">{s.sourceName}</span>
                          <span className="text-slate-400">({s.associatedEntity || item.entityName})</span>
                        </div>
                      ))}
                    </td>
                    <td className="py-3 px-3">
                      {hasConflict ? (
                        <span className="bg-amber-950 text-amber-300 px-2 py-0.5 rounded border border-amber-800 text-[10px] font-semibold flex items-center w-fit">
                          <AlertTriangle className="w-3 h-3 mr-1" /> CONFLICT CASE
                        </span>
                      ) : (
                        <span className="bg-emerald-950 text-emerald-300 px-2 py-0.5 rounded border border-emerald-800 text-[10px] font-semibold flex items-center w-fit">
                          <CheckCircle2 className="w-3 h-3 mr-1" /> CORROBORATED
                        </span>
                      )}
                    </td>
                    <td className="py-3 px-3 text-slate-400 max-w-xs truncate">{item.notes}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Attribution Boundary Matrix */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-lg p-5">
        <h3 className="text-xs font-mono uppercase text-slate-400 border-b border-slate-800 pb-3 mb-4 font-semibold">
          Evidentiary Attribution Boundary Framework
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 font-mono text-xs">
          <div className="p-4 rounded border bg-emerald-950/30 border-emerald-800/60">
            <div className="flex items-center justify-between mb-2">
              <span className="text-emerald-400 font-semibold">DIRECT EVIDENCE</span>
              <span className="text-[10px] bg-emerald-900 text-emerald-200 px-1.5 py-0.5 rounded">CLASS 1</span>
            </div>
            <p className="text-slate-300 text-[11px] leading-relaxed">
              Known VASP-associated address/cluster supported by strong on-chain evidence match.
            </p>
          </div>

          <div className="p-4 rounded border bg-blue-950/30 border-blue-800/60">
            <div className="flex items-center justify-between mb-2">
              <span className="text-blue-400 font-semibold">INFERRED ASSOCIATION</span>
              <span className="text-[10px] bg-blue-900 text-blue-200 px-1.5 py-0.5 rounded">CLASS 2</span>
            </div>
            <p className="text-slate-300 text-[11px] leading-relaxed">
              Relationship inferred from transaction/behavioral evidence without exact verified address match.
            </p>
          </div>

          <div className="p-4 rounded border bg-amber-950/30 border-amber-800/60">
            <div className="flex items-center justify-between mb-2">
              <span className="text-amber-400 font-semibold">UNKNOWN</span>
              <span className="text-[10px] bg-amber-900 text-amber-200 px-1.5 py-0.5 rounded">CLASS 3</span>
            </div>
            <p className="text-slate-300 text-[11px] leading-relaxed">
              Insufficient evidence to establish a VASP association.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
